name: Build container image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

    - name: Login to ECR
      uses: docker/login-action@v1
      with:
        registry: 563616081143.dkr.ecr.us-east-2.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    - name: Update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_REGISTRY: "563616081143.dkr.ecr.us-east-2.amazonaws.com"
        IMAGE_NAME: "gigitest/test-repo2docker-action"
