name: Build container image

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker

    steps:
    - name: checkout files in repo
      uses: actions/checkout@main

    - name: Login to GAR
      uses: docker/login-action@v1
      with:
        registry: europe-west3-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}
        
    - name: Update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_REGISTRY: europe-west3-docker.pkg.dev
        IMAGE_NAME: ${{ secrets.GCP_PROJECT_ID }}/gha-builder-test/test-repo2docker-action
    
