name: Build container image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout files in repo
      uses: actions/checkout@main

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Configure docker
      run: |
        gcloud auth configure-docker -q
        
    - name: Update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_REGISTRY: eu.gcr.io
        IMAGE_NAME: ${{ secrets.GCP_PROJECT_ID }}/test-repo2docker-action
    
