name: Build container image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

#     - name: Login to ECR
#       uses: docker/login-action@v1
#       with:
#         registry: 563616081143.dkr.ecr.us-east-2.amazonaws.com
#         username: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to Public ECR
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws/p7w3e1x7
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
        AWS_REGION: us-east-2
      
    - name: Update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_REGISTRY: "public.ecr.aws/p7w3e1x7"
        IMAGE_NAME: "gigitest/test-repo2docker-action-public"
