name: Build container image

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker

    steps:
    - name: checkout files in repo
      uses: actions/checkout@main

    - name: Update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.ACR_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.LOGIN_SERVER }}
        IMAGE_NAME: "test-image"
