name: Build container image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker

    steps:
    - name: checkout files in repo
      uses: actions/checkout@main

#     - name: Set up gcloud
#       uses: google-github-actions/setup-gcloud@master
#       with:
#         project_id: ${{ secrets.GCP_PROJECT_ID }}
#         service_account_key: ${{ secrets.GCP_SA_KEY }}
#         service_account_email: ${{ secrets.GCP_SA_EMAIL }}
#         export_default_credentials: false
        
    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}
    
    # Configure docker to use the gcloud command-line tool as a credential helper
#     - name: Configure docker
#       run: |
#         gcloud auth configure-docker
#         gcloud info
        
    - name: Update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_REGISTRY: eu.gcr.io
        IMAGE_NAME: ${{ secrets.GCP_PROJECT_ID }}/test-repo2docker-action
    
