name: Build container image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker
    steps:
    - name: checkout files in repo
      uses: actions/checkout@main

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Login to ECR
      uses: docker/login-action@v1
      with:
        registry: 563616081143.dkr.ecr.us-east-2.amazonaws.com

    - name: Update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_REGISTRY: "563616081143.dkr.ecr.us-east-2.amazonaws.com"
        IMAGE_NAME: "gigitest/test-repo2docker-action"
